services:
  # web:
  #   image: python:3.13
  #   container_name: django_app
  #   command: >
  #     bash -c "pip install --no-cache-dir -r requirements.txt &&
  #            python manage.py migrate &&
  #            python manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=1
  #     - DJANGO_ALLOWED_HOSTS=localhost
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
volumes:
  user_postgres_data: